// 특수문자 데이터
const symbolData = {
  emoji: [
    { char: '😀', name: '웃는 얼굴' },
    { char: '😃', name: '활짝 웃는 얼굴' },
    { char: '😄', name: '눈웃음' },
    { char: '😁', name: '활짝 웃음' },
    { char: '😆', name: '찡긋 웃음' },
    { char: '😅', name: '민망한 웃음' },
    { char: '🤣', name: '빵터짐' },
    { char: '😂', name: '눈물 웃음' },
    { char: '🙂', name: '살짝 웃음' },
    { char: '😊', name: '수줍은 웃음' },
    { char: '😇', name: '천사' },
    { char: '🥰', name: '사랑스러움' },
    { char: '😍', name: '하트 눈' },
    { char: '🤩', name: '별 눈' },
    { char: '😘', name: '뽀뽀' },
    { char: '😗', name: '입술' },
    { char: '😚', name: '키스' },
    { char: '😋', name: '맛있음' },
    { char: '😛', name: '메롱' },
    { char: '😜', name: '찡긋 메롱' },
    { char: '🤪', name: '장난' },
    { char: '😝', name: '눈감고 메롱' },
    { char: '🤑', name: '돈' },
    { char: '🤗', name: '허그' },
    { char: '🤭', name: '앗' },
    { char: '🤫', name: '쉿' },
    { char: '🤔', name: '생각' },
    { char: '🤐', name: '입봉' },
    { char: '🤨', name: '의심' },
    { char: '😐', name: '무표정' },
    { char: '😑', name: '지침' },
    { char: '😶', name: '입없음' },
    { char: '😏', name: '능글' },
    { char: '😒', name: '지루함' },
    { char: '🙄', name: '눈굴림' },
    { char: '😬', name: '이 드러냄' },
    { char: '😮‍💨', name: '한숨' },
    { char: '🤥', name: '거짓말' },
    { char: '😌', name: '평온' },
    { char: '😔', name: '수심' },
    { char: '😪', name: '졸림' },
    { char: '🤤', name: '침흘림' },
    { char: '😴', name: '잠' },
    { char: '😷', name: '마스크' },
    { char: '🤒', name: '아픔' },
    { char: '🤕', name: '다침' },
    { char: '🤢', name: '메스꺼움' },
    { char: '🤮', name: '구토' },
    { char: '🤧', name: '재채기' },
    { char: '🥵', name: '더움' },
    { char: '🥶', name: '추움' },
    { char: '😵', name: '어지러움' },
    { char: '🤯', name: '멘붕' },
    { char: '🤠', name: '카우보이' },
    { char: '🥳', name: '파티' },
    { char: '😎', name: '쿨' },
    { char: '🤓', name: '안경' },
    { char: '🧐', name: '탐구' },
    { char: '😕', name: '당혹' },
    { char: '😟', name: '걱정' },
    { char: '🙁', name: '실망' },
    { char: '😮', name: '놀람' },
    { char: '😯', name: '멍' },
    { char: '😲', name: '깜놀' },
    { char: '😳', name: '당황' },
    { char: '🥺', name: '애원' },
    { char: '😦', name: '걱정스러움' },
    { char: '😧', name: '고뇌' },
    { char: '😨', name: '두려움' },
    { char: '😰', name: '식은땀' },
    { char: '😥', name: '슬픔' },
    { char: '😢', name: '눈물' },
    { char: '😭', name: '엉엉' },
    { char: '😱', name: '비명' },
    { char: '😖', name: '혼란' },
    { char: '😣', name: '참음' },
    { char: '😞', name: '낙담' },
    { char: '😓', name: '땀' },
    { char: '😩', name: '지쳐' },
    { char: '😫', name: '피곤' },
    { char: '🥱', name: '하품' },
    { char: '😤', name: '화남' },
    { char: '😡', name: '분노' },
    { char: '😠', name: '짜증' },
    { char: '🤬', name: '욕설' },
    { char: '👍', name: '엄지척' },
    { char: '👎', name: '엄지 아래' },
    { char: '👏', name: '박수' },
    { char: '🙌', name: '만세' },
    { char: '👐', name: '열린 손' },
    { char: '🤲', name: '손바닥' },
    { char: '🤝', name: '악수' },
    { char: '🙏', name: '기도' },
    { char: '✌️', name: '브이' },
    { char: '🤞', name: '행운' },
    { char: '🤟', name: '사랑해' },
    { char: '🤘', name: '락' },
    { char: '👌', name: '오케이' },
    { char: '🤌', name: '이탈리안' },
    { char: '🤏', name: '조금' },
    { char: '👈', name: '왼쪽' },
    { char: '👉', name: '오른쪽' },
    { char: '👆', name: '위' },
    { char: '👇', name: '아래' },
    { char: '☝️', name: '검지' },
    { char: '✋', name: '손' },
    { char: '🤚', name: '뒤집은 손' },
    { char: '🖐️', name: '펼친 손' },
    { char: '🖖', name: '벌컨' },
    { char: '👋', name: '손인사' },
    { char: '🤙', name: '전화' },
    { char: '💪', name: '근육' },
    { char: '🦾', name: '로봇팔' },
    { char: '❤️', name: '빨간 하트' },
    { char: '🧡', name: '주황 하트' },
    { char: '💛', name: '노랑 하트' },
    { char: '💚', name: '초록 하트' },
    { char: '💙', name: '파랑 하트' },
    { char: '💜', name: '보라 하트' },
    { char: '🖤', name: '검정 하트' },
    { char: '🤍', name: '흰 하트' },
    { char: '💔', name: '상처' },
    { char: '💕', name: '두 하트' },
    { char: '💖', name: '반짝 하트' },
    { char: '💗', name: '커지는 하트' },
    { char: '💘', name: '화살 하트' },
    { char: '💝', name: '선물 하트' },
    { char: '💞', name: '회전 하트' },
    { char: '🔥', name: '불' },
    { char: '✨', name: '반짝임' },
    { char: '⭐', name: '별' },
    { char: '🌟', name: '빛나는 별' },
    { char: '💫', name: '어지러운 별' },
    { char: '🎉', name: '파티' },
    { char: '🎊', name: '축하' },
    { char: '🎁', name: '선물' },
    { char: '🎈', name: '풍선' },
    { char: '🎂', name: '케이크' },
    { char: '🍰', name: '조각케이크' },
    { char: '☀️', name: '태양' },
    { char: '🌈', name: '무지개' },
    { char: '☁️', name: '구름' },
    { char: '🌙', name: '달' },
    { char: '⚡', name: '번개' },
    { char: '💧', name: '물방울' },
    { char: '🌸', name: '벚꽃' },
    { char: '🌺', name: '히비스커스' },
    { char: '🌷', name: '튤립' },
    { char: '🌹', name: '장미' },
    { char: '🍀', name: '네잎클로버' }
  ],
  arrow: [
    { char: '←', name: '왼쪽 화살표' },
    { char: '→', name: '오른쪽 화살표' },
    { char: '↑', name: '위쪽 화살표' },
    { char: '↓', name: '아래쪽 화살표' },
    { char: '↔', name: '좌우 화살표' },
    { char: '↕', name: '상하 화살표' },
    { char: '↖', name: '왼쪽 위 화살표' },
    { char: '↗', name: '오른쪽 위 화살표' },
    { char: '↘', name: '오른쪽 아래 화살표' },
    { char: '↙', name: '왼쪽 아래 화살표' },
    { char: '⇐', name: '이중 왼쪽' },
    { char: '⇒', name: '이중 오른쪽' },
    { char: '⇑', name: '이중 위쪽' },
    { char: '⇓', name: '이중 아래쪽' },
    { char: '⇔', name: '이중 좌우' },
    { char: '⇕', name: '이중 상하' },
    { char: '➜', name: '굵은 화살표' },
    { char: '➔', name: '채운 화살표' },
    { char: '➝', name: '가는 화살표' },
    { char: '➞', name: '뾰족 화살표' },
    { char: '➟', name: '점선 화살표' },
    { char: '➠', name: '3D 화살표' },
    { char: '➡', name: '굵은 오른쪽' },
    { char: '➢', name: '삼각 화살표' },
    { char: '➣', name: '채운 삼각' },
    { char: '➤', name: '검은 삼각' },
    { char: '➥', name: '꺾인 오른쪽' },
    { char: '➦', name: '꺾인 왼쪽' },
    { char: '➧', name: '둥근 화살표' },
    { char: '➨', name: '3D 오른쪽' },
    { char: '➩', name: '빈 화살표' },
    { char: '➪', name: '둥근 꼬리' },
    { char: '➫', name: '노치 화살표' },
    { char: '➬', name: '채운 노치' },
    { char: '➭', name: '깃털 화살표' },
    { char: '➮', name: '채운 깃털' },
    { char: '➯', name: '3D 빈 화살표' },
    { char: '➱', name: '끝 넓은 화살표' },
    { char: '➲', name: '원형 화살표' },
    { char: '▶', name: '재생' },
    { char: '◀', name: '이전' },
    { char: '▲', name: '위 삼각형' },
    { char: '▼', name: '아래 삼각형' },
    { char: '►', name: '검은 재생' },
    { char: '◄', name: '검은 이전' },
    { char: '↩', name: '되돌리기' },
    { char: '↪', name: '다시하기' },
    { char: '↰', name: '왼쪽 꺾임 위' },
    { char: '↱', name: '오른쪽 꺾임 위' },
    { char: '↲', name: '왼쪽 꺾임 아래' },
    { char: '↳', name: '오른쪽 꺾임 아래' },
    { char: '↴', name: '아래 오른쪽' },
    { char: '↵', name: '엔터' },
    { char: '⟵', name: '긴 왼쪽' },
    { char: '⟶', name: '긴 오른쪽' },
    { char: '⟷', name: '긴 좌우' },
    { char: '⤴', name: '위로 꺾임' },
    { char: '⤵', name: '아래로 꺾임' },
    { char: '↺', name: '반시계 회전' },
    { char: '↻', name: '시계 회전' },
    { char: '⥀', name: '위 반시계' },
    { char: '⥁', name: '아래 시계' }
  ],
  star: [
    { char: '★', name: '검은 별' },
    { char: '☆', name: '흰 별' },
    { char: '✦', name: '검은 사각별' },
    { char: '✧', name: '흰 사각별' },
    { char: '✩', name: '스트레스 별' },
    { char: '✪', name: '원 안의 별' },
    { char: '✫', name: '열린 별' },
    { char: '✬', name: '열린 별2' },
    { char: '✭', name: '아웃라인 별' },
    { char: '✮', name: '아웃라인 별2' },
    { char: '✯', name: '핀휠 별' },
    { char: '✰', name: '그림자 별' },
    { char: '✡', name: '다윗의 별' },
    { char: '✴', name: '8각 별' },
    { char: '✵', name: '8각 별 테두리' },
    { char: '✶', name: '6각 별' },
    { char: '✷', name: '6각 별 테두리' },
    { char: '✸', name: '8각 별 채움' },
    { char: '✹', name: '12각 별' },
    { char: '✺', name: '16각 별' },
    { char: '⋆', name: '작은 별' },
    { char: '≛', name: '별 등호' },
    { char: '♥', name: '검은 하트' },
    { char: '♡', name: '흰 하트' },
    { char: '❤', name: '빨간 하트' },
    { char: '❥', name: '기울어진 하트' },
    { char: '❣', name: '느낌표 하트' },
    { char: '❦', name: '꽃 하트' },
    { char: '❧', name: '회전 꽃 하트' },
    { char: '❤️‍🔥', name: '불타는 하트' },
    { char: '❤️‍🩹', name: '치유 하트' },
    { char: '💓', name: '두근 하트' },
    { char: '💔', name: '깨진 하트' },
    { char: '🖤', name: '검은 하트 이모지' },
    { char: '🤍', name: '흰 하트 이모지' },
    { char: '💜', name: '보라 하트 이모지' },
    { char: '💙', name: '파랑 하트 이모지' },
    { char: '💚', name: '초록 하트 이모지' },
    { char: '💛', name: '노랑 하트 이모지' },
    { char: '🧡', name: '주황 하트 이모지' }
  ],
  check: [
    { char: '✓', name: '체크' },
    { char: '✔', name: '굵은 체크' },
    { char: '✕', name: '엑스' },
    { char: '✖', name: '굵은 엑스' },
    { char: '✗', name: '투표 엑스' },
    { char: '✘', name: '굵은 투표 엑스' },
    { char: '☐', name: '빈 체크박스' },
    { char: '☑', name: '체크된 박스' },
    { char: '☒', name: '엑스 박스' },
    { char: '✅', name: '초록 체크' },
    { char: '❌', name: '빨간 엑스' },
    { char: '❎', name: '초록 엑스' },
    { char: '○', name: '빈 원' },
    { char: '●', name: '검은 원' },
    { char: '◎', name: '이중 원' },
    { char: '◉', name: '점 원' },
    { char: '◌', name: '점선 원' },
    { char: '◍', name: '수직선 원' },
    { char: '◐', name: '왼쪽 반원' },
    { char: '◑', name: '오른쪽 반원' },
    { char: '◒', name: '위 반원' },
    { char: '◓', name: '아래 반원' },
    { char: '◔', name: '사분원 1' },
    { char: '◕', name: '사분원 3' },
    { char: '◖', name: '왼쪽 반' },
    { char: '◗', name: '오른쪽 반' },
    { char: '⊙', name: '점원' },
    { char: '⊚', name: '원 안의 원' },
    { char: '⊛', name: '별 원' },
    { char: '⊜', name: '등호 원' },
    { char: '⊝', name: '마이너스 원' },
    { char: '⦿', name: '점 있는 원' },
    { char: '◦', name: '작은 빈 원' },
    { char: '•', name: '불릿' },
    { char: '‣', name: '삼각 불릿' },
    { char: '⁃', name: '하이픈 불릿' },
    { char: '⁌', name: '검은 사각 불릿' },
    { char: '⁍', name: '흰 사각 불릿' },
    { char: '⦾', name: '흰 점 원' },
    { char: '⦁', name: '큰 불릿' }
  ],
  bracket: [
    { char: '「', name: '왼쪽 낫표' },
    { char: '」', name: '오른쪽 낫표' },
    { char: '『', name: '왼쪽 겹낫표' },
    { char: '』', name: '오른쪽 겹낫표' },
    { char: '【', name: '왼쪽 굵은 대괄호' },
    { char: '】', name: '오른쪽 굵은 대괄호' },
    { char: '〈', name: '왼쪽 홑화살괄호' },
    { char: '〉', name: '오른쪽 홑화살괄호' },
    { char: '《', name: '왼쪽 겹화살괄호' },
    { char: '》', name: '오른쪽 겹화살괄호' },
    { char: '〔', name: '왼쪽 거북이괄호' },
    { char: '〕', name: '오른쪽 거북이괄호' },
    { char: '〖', name: '왼쪽 흰괄호' },
    { char: '〗', name: '오른쪽 흰괄호' },
    { char: '〘', name: '왼쪽 겹괄호' },
    { char: '〙', name: '오른쪽 겹괄호' },
    { char: '〚', name: '왼쪽 흰대괄호' },
    { char: '〛', name: '오른쪽 흰대괄호' },
    { char: '（', name: '전각 왼쪽 소괄호' },
    { char: '）', name: '전각 오른쪽 소괄호' },
    { char: '［', name: '전각 왼쪽 대괄호' },
    { char: '］', name: '전각 오른쪽 대괄호' },
    { char: '｛', name: '전각 왼쪽 중괄호' },
    { char: '｝', name: '전각 오른쪽 중괄호' },
    { char: '⟨', name: '수학 왼쪽 꺾쇠' },
    { char: '⟩', name: '수학 오른쪽 꺾쇠' },
    { char: '⟪', name: '수학 왼쪽 겹꺾쇠' },
    { char: '⟫', name: '수학 오른쪽 겹꺾쇠' },
    { char: '⦃', name: '왼쪽 흰중괄호' },
    { char: '⦄', name: '오른쪽 흰중괄호' },
    { char: '"', name: '왼쪽 쌍따옴표' },
    { char: '"', name: '오른쪽 쌍따옴표' },
    { char: ''', name: '왼쪽 작은따옴표' },
    { char: ''', name: '오른쪽 작은따옴표' },
    { char: '‚', name: '아래 작은따옴표' },
    { char: '„', name: '아래 쌍따옴표' },
    { char: '‛', name: '역 작은따옴표' },
    { char: '‟', name: '역 쌍따옴표' },
    { char: '«', name: '왼쪽 길머맷' },
    { char: '»', name: '오른쪽 길머맷' },
    { char: '‹', name: '왼쪽 홑길머맷' },
    { char: '›', name: '오른쪽 홑길머맷' },
    { char: '〝', name: '역 쌍따옴표 위' },
    { char: '〞', name: '쌍따옴표 위' },
    { char: '〟', name: '아래 쌍따옴표2' }
  ],
  number: [
    { char: '①', name: '원 1' },
    { char: '②', name: '원 2' },
    { char: '③', name: '원 3' },
    { char: '④', name: '원 4' },
    { char: '⑤', name: '원 5' },
    { char: '⑥', name: '원 6' },
    { char: '⑦', name: '원 7' },
    { char: '⑧', name: '원 8' },
    { char: '⑨', name: '원 9' },
    { char: '⑩', name: '원 10' },
    { char: '⑪', name: '원 11' },
    { char: '⑫', name: '원 12' },
    { char: '⑬', name: '원 13' },
    { char: '⑭', name: '원 14' },
    { char: '⑮', name: '원 15' },
    { char: '⑯', name: '원 16' },
    { char: '⑰', name: '원 17' },
    { char: '⑱', name: '원 18' },
    { char: '⑲', name: '원 19' },
    { char: '⑳', name: '원 20' },
    { char: '❶', name: '검은 원 1' },
    { char: '❷', name: '검은 원 2' },
    { char: '❸', name: '검은 원 3' },
    { char: '❹', name: '검은 원 4' },
    { char: '❺', name: '검은 원 5' },
    { char: '❻', name: '검은 원 6' },
    { char: '❼', name: '검은 원 7' },
    { char: '❽', name: '검은 원 8' },
    { char: '❾', name: '검은 원 9' },
    { char: '❿', name: '검은 원 10' },
    { char: '㉠', name: '원 ㄱ' },
    { char: '㉡', name: '원 ㄴ' },
    { char: '㉢', name: '원 ㄷ' },
    { char: '㉣', name: '원 ㄹ' },
    { char: '㉤', name: '원 ㅁ' },
    { char: '㉥', name: '원 ㅂ' },
    { char: '㉦', name: '원 ㅅ' },
    { char: '㉧', name: '원 ㅇ' },
    { char: '㉨', name: '원 ㅈ' },
    { char: '㉩', name: '원 ㅊ' },
    { char: '㉪', name: '원 ㅋ' },
    { char: '㉫', name: '원 ㅌ' },
    { char: '㉬', name: '원 ㅍ' },
    { char: '㉭', name: '원 ㅎ' },
    { char: 'ⓐ', name: '원 a' },
    { char: 'ⓑ', name: '원 b' },
    { char: 'ⓒ', name: '원 c' },
    { char: 'ⓓ', name: '원 d' },
    { char: 'ⓔ', name: '원 e' },
    { char: 'ⓕ', name: '원 f' },
    { char: 'ⓖ', name: '원 g' },
    { char: 'ⓗ', name: '원 h' },
    { char: 'ⓘ', name: '원 i' },
    { char: 'ⓙ', name: '원 j' },
    { char: 'ⓚ', name: '원 k' },
    { char: 'ⓛ', name: '원 l' },
    { char: 'ⓜ', name: '원 m' },
    { char: 'ⓝ', name: '원 n' },
    { char: 'ⓞ', name: '원 o' },
    { char: 'ⓟ', name: '원 p' },
    { char: 'ⓠ', name: '원 q' },
    { char: 'ⓡ', name: '원 r' },
    { char: 'ⓢ', name: '원 s' },
    { char: 'ⓣ', name: '원 t' },
    { char: 'ⓤ', name: '원 u' },
    { char: 'ⓥ', name: '원 v' },
    { char: 'ⓦ', name: '원 w' },
    { char: 'ⓧ', name: '원 x' },
    { char: 'ⓨ', name: '원 y' },
    { char: 'ⓩ', name: '원 z' },
    { char: 'Ⓐ', name: '원 A' },
    { char: 'Ⓑ', name: '원 B' },
    { char: 'Ⓒ', name: '원 C' },
    { char: 'Ⓓ', name: '원 D' },
    { char: 'Ⓔ', name: '원 E' },
    { char: 'Ⓕ', name: '원 F' },
    { char: 'Ⓖ', name: '원 G' },
    { char: 'Ⓗ', name: '원 H' },
    { char: 'Ⓘ', name: '원 I' },
    { char: 'Ⓙ', name: '원 J' },
    { char: 'Ⓚ', name: '원 K' },
    { char: 'Ⓛ', name: '원 L' },
    { char: 'Ⓜ', name: '원 M' },
    { char: 'Ⓝ', name: '원 N' },
    { char: 'Ⓞ', name: '원 O' },
    { char: 'Ⓟ', name: '원 P' },
    { char: 'Ⓠ', name: '원 Q' },
    { char: 'Ⓡ', name: '원 R' },
    { char: 'Ⓢ', name: '원 S' },
    { char: 'Ⓣ', name: '원 T' },
    { char: 'Ⓤ', name: '원 U' },
    { char: 'Ⓥ', name: '원 V' },
    { char: 'Ⓦ', name: '원 W' },
    { char: 'Ⓧ', name: '원 X' },
    { char: 'Ⓨ', name: '원 Y' },
    { char: 'Ⓩ', name: '원 Z' },
    { char: 'Ⅰ', name: '로마 1' },
    { char: 'Ⅱ', name: '로마 2' },
    { char: 'Ⅲ', name: '로마 3' },
    { char: 'Ⅳ', name: '로마 4' },
    { char: 'Ⅴ', name: '로마 5' },
    { char: 'Ⅵ', name: '로마 6' },
    { char: 'Ⅶ', name: '로마 7' },
    { char: 'Ⅷ', name: '로마 8' },
    { char: 'Ⅸ', name: '로마 9' },
    { char: 'Ⅹ', name: '로마 10' },
    { char: 'ⅰ', name: '소문자 로마 1' },
    { char: 'ⅱ', name: '소문자 로마 2' },
    { char: 'ⅲ', name: '소문자 로마 3' },
    { char: 'ⅳ', name: '소문자 로마 4' },
    { char: 'ⅴ', name: '소문자 로마 5' }
  ],
  math: [
    { char: '+', name: '더하기' },
    { char: '−', name: '빼기' },
    { char: '±', name: '플러스마이너스' },
    { char: '×', name: '곱하기' },
    { char: '÷', name: '나누기' },
    { char: '=', name: '등호' },
    { char: '≠', name: '같지 않음' },
    { char: '≈', name: '거의 같음' },
    { char: '≡', name: '항등' },
    { char: '≢', name: '항등 아님' },
    { char: '<', name: '작다' },
    { char: '>', name: '크다' },
    { char: '≤', name: '작거나 같다' },
    { char: '≥', name: '크거나 같다' },
    { char: '≪', name: '훨씬 작다' },
    { char: '≫', name: '훨씬 크다' },
    { char: '∞', name: '무한대' },
    { char: '√', name: '제곱근' },
    { char: '∛', name: '세제곱근' },
    { char: '∜', name: '네제곱근' },
    { char: '%', name: '퍼센트' },
    { char: '‰', name: '천분율' },
    { char: '‱', name: '만분율' },
    { char: '∑', name: '시그마' },
    { char: '∏', name: '곱 기호' },
    { char: '∫', name: '적분' },
    { char: '∬', name: '이중 적분' },
    { char: '∭', name: '삼중 적분' },
    { char: '∂', name: '편미분' },
    { char: '∇', name: '나블라' },
    { char: '∆', name: '델타' },
    { char: 'π', name: '파이' },
    { char: 'Σ', name: '대문자 시그마' },
    { char: 'Ω', name: '오메가' },
    { char: 'α', name: '알파' },
    { char: 'β', name: '베타' },
    { char: 'γ', name: '감마' },
    { char: 'δ', name: '소문자 델타' },
    { char: 'ε', name: '엡실론' },
    { char: 'θ', name: '세타' },
    { char: 'λ', name: '람다' },
    { char: 'μ', name: '뮤' },
    { char: 'φ', name: '파이(그리스)' },
    { char: '∈', name: '원소' },
    { char: '∉', name: '원소 아님' },
    { char: '∋', name: '포함' },
    { char: '⊂', name: '부분집합' },
    { char: '⊃', name: '상위집합' },
    { char: '⊆', name: '부분집합 같음' },
    { char: '⊇', name: '상위집합 같음' },
    { char: '∪', name: '합집합' },
    { char: '∩', name: '교집합' },
    { char: '∅', name: '공집합' },
    { char: '∀', name: '모든' },
    { char: '∃', name: '존재' },
    { char: '∄', name: '존재하지 않음' },
    { char: '∴', name: '그러므로' },
    { char: '∵', name: '왜냐하면' },
    { char: '∝', name: '비례' },
    { char: '∟', name: '직각' },
    { char: '∠', name: '각도' },
    { char: '⊥', name: '수직' },
    { char: '∥', name: '평행' },
    { char: '≅', name: '합동' },
    { char: '∼', name: '닮음' },
    { char: '¬', name: '부정' },
    { char: '∧', name: '논리곱' },
    { char: '∨', name: '논리합' },
    { char: '⊕', name: '배타적 논리합' },
    { char: '⊗', name: '텐서곱' },
    { char: '⊙', name: '점곱' }
  ],
  unit: [
    { char: '°', name: '도' },
    { char: '℃', name: '섭씨' },
    { char: '℉', name: '화씨' },
    { char: '㎜', name: '밀리미터' },
    { char: '㎝', name: '센티미터' },
    { char: '㎞', name: '킬로미터' },
    { char: '㎎', name: '밀리그램' },
    { char: '㎏', name: '킬로그램' },
    { char: '㎖', name: '밀리리터' },
    { char: '㎗', name: '데시리터' },
    { char: 'ℓ', name: '리터' },
    { char: '㎡', name: '제곱미터' },
    { char: '㎢', name: '제곱킬로미터' },
    { char: '㎥', name: '세제곱미터' },
    { char: '㏊', name: '헥타르' },
    { char: '㎐', name: '헤르츠' },
    { char: '㎑', name: '킬로헤르츠' },
    { char: '㎒', name: '메가헤르츠' },
    { char: '㎓', name: '기가헤르츠' },
    { char: '㎴', name: '피코초' },
    { char: '㎵', name: '나노초' },
    { char: '㎶', name: '마이크로초' },
    { char: '㎷', name: '밀리초' },
    { char: '㎸', name: '킬로볼트' },
    { char: '㎹', name: '메가볼트' },
    { char: '㎃', name: '밀리암페어' },
    { char: '㎄', name: '킬로암페어' },
    { char: '㎅', name: '킬로바이트' },
    { char: '㎆', name: '메가바이트' },
    { char: '㎇', name: '기가바이트' },
    { char: '㎈', name: '칼로리' },
    { char: '㎉', name: '킬로칼로리' },
    { char: '㎊', name: '피코패럿' },
    { char: '㎋', name: '나노패럿' },
    { char: '㎌', name: '마이크로패럿' },
    { char: '㎍', name: '마이크로그램' },
    { char: '㎕', name: '마이크로리터' },
    { char: '㎙', name: '펨토미터' },
    { char: '㎚', name: '나노미터' },
    { char: '㎛', name: '마이크로미터' },
    { char: '㎟', name: '제곱밀리미터' },
    { char: '㎠', name: '제곱센티미터' },
    { char: '㎤', name: '세제곱센티미터' },
    { char: '㎦', name: '세제곱킬로미터' },
    { char: '㏄', name: 'cc' },
    { char: '㏂', name: 'AM' },
    { char: '㏘', name: 'PM' },
    { char: '㍱', name: '헥토파스칼' },
    { char: '㍲', name: '다' },
    { char: '㍳', name: '아우' },
    { char: '㍴', name: '바' },
    { char: '㍵', name: '오브이' },
    { char: '㍶', name: '피시' },
    { char: '㍷', name: '디엠' },
    { char: '㍸', name: '디엠제곱' },
    { char: '㍹', name: '디엠세제곱' },
    { char: 'Å', name: '옹스트롬' },
    { char: '㏈', name: '데시벨' },
    { char: '№', name: '번호' },
    { char: '℡', name: '전화' },
    { char: '㏀', name: '킬로옴' },
    { char: '㏁', name: '메가옴' },
    { char: '㎩', name: '파스칼' },
    { char: '㎪', name: '킬로파스칼' },
    { char: '㎫', name: '메가파스칼' },
    { char: '㎬', name: '기가파스칼' },
    { char: '㎭', name: '라드' },
    { char: '㎮', name: '라드/초' },
    { char: '㎯', name: '라드/제곱초' },
    { char: '㎰', name: '피코초2' },
    { char: '㎱', name: '나노초2' },
    { char: '㎲', name: '마이크로초2' },
    { char: '㎳', name: '밀리초2' },
    { char: '㎺', name: '피코와트' },
    { char: '㎻', name: '나노와트' },
    { char: '㎼', name: '마이크로와트' },
    { char: '㎽', name: '밀리와트' },
    { char: '㎾', name: '킬로와트' },
    { char: '㎿', name: '메가와트' },
    { char: '㏃', name: '베크렐' },
    { char: '㏅', name: '캔델라' },
    { char: '㏆', name: '쿨롬/킬로그램' },
    { char: '㏇', name: '코' },
    { char: '㏉', name: '그레이' },
    { char: '㏊', name: '헥타르2' },
    { char: '㏋', name: '마력' },
    { char: '㏌', name: '인치' },
    { char: '㏍', name: '케이케이' },
    { char: '㏎', name: '케이엠' },
    { char: '㏏', name: '노트' },
    { char: '㏐', name: '루멘' }
  ],
  line: [
    { char: '─', name: '가로선' },
    { char: '━', name: '굵은 가로선' },
    { char: '│', name: '세로선' },
    { char: '┃', name: '굵은 세로선' },
    { char: '┌', name: '왼쪽 위 모서리' },
    { char: '┐', name: '오른쪽 위 모서리' },
    { char: '└', name: '왼쪽 아래 모서리' },
    { char: '┘', name: '오른쪽 아래 모서리' },
    { char: '├', name: '왼쪽 T자' },
    { char: '┤', name: '오른쪽 T자' },
    { char: '┬', name: '위 T자' },
    { char: '┴', name: '아래 T자' },
    { char: '┼', name: '십자' },
    { char: '┏', name: '굵은 왼쪽 위' },
    { char: '┓', name: '굵은 오른쪽 위' },
    { char: '┗', name: '굵은 왼쪽 아래' },
    { char: '┛', name: '굵은 오른쪽 아래' },
    { char: '┣', name: '굵은 왼쪽 T' },
    { char: '┫', name: '굵은 오른쪽 T' },
    { char: '┳', name: '굵은 위 T' },
    { char: '┻', name: '굵은 아래 T' },
    { char: '╋', name: '굵은 십자' },
    { char: '╔', name: '이중선 왼쪽 위' },
    { char: '╗', name: '이중선 오른쪽 위' },
    { char: '╚', name: '이중선 왼쪽 아래' },
    { char: '╝', name: '이중선 오른쪽 아래' },
    { char: '╠', name: '이중선 왼쪽 T' },
    { char: '╣', name: '이중선 오른쪽 T' },
    { char: '╦', name: '이중선 위 T' },
    { char: '╩', name: '이중선 아래 T' },
    { char: '╬', name: '이중선 십자' },
    { char: '═', name: '이중 가로선' },
    { char: '║', name: '이중 세로선' },
    { char: '■', name: '검은 사각형' },
    { char: '□', name: '흰 사각형' },
    { char: '▪', name: '작은 검은 사각형' },
    { char: '▫', name: '작은 흰 사각형' },
    { char: '▬', name: '검은 직사각형' },
    { char: '▭', name: '흰 직사각형' },
    { char: '▮', name: '세로 직사각형' },
    { char: '▯', name: '흰 세로 직사각형' },
    { char: '▲', name: '위 삼각형' },
    { char: '△', name: '흰 위 삼각형' },
    { char: '▴', name: '작은 위 삼각형' },
    { char: '▵', name: '작은 흰 위 삼각형' },
    { char: '▼', name: '아래 삼각형' },
    { char: '▽', name: '흰 아래 삼각형' },
    { char: '▾', name: '작은 아래 삼각형' },
    { char: '▿', name: '작은 흰 아래 삼각형' },
    { char: '◀', name: '왼쪽 삼각형' },
    { char: '◁', name: '흰 왼쪽 삼각형' },
    { char: '◂', name: '작은 왼쪽 삼각형' },
    { char: '◃', name: '작은 흰 왼쪽 삼각형' },
    { char: '▶', name: '오른쪽 삼각형' },
    { char: '▷', name: '흰 오른쪽 삼각형' },
    { char: '▸', name: '작은 오른쪽 삼각형' },
    { char: '▹', name: '작은 흰 오른쪽 삼각형' },
    { char: '◆', name: '검은 다이아몬드' },
    { char: '◇', name: '흰 다이아몬드' },
    { char: '◈', name: '다이아몬드 점' },
    { char: '◉', name: '점원 도형' },
    { char: '◊', name: '마름모' },
    { char: '○', name: '원' },
    { char: '●', name: '검은 원' },
    { char: '◐', name: '왼쪽 반원' },
    { char: '◑', name: '오른쪽 반원' },
    { char: '◒', name: '위 반원' },
    { char: '◓', name: '아래 반원' },
    { char: '◔', name: '4분원 1' },
    { char: '◕', name: '4분원 3' },
    { char: '◖', name: '왼쪽 반' },
    { char: '◗', name: '오른쪽 반' },
    { char: '◘', name: '역 불릿' },
    { char: '◙', name: '역 원' },
    { char: '◚', name: '위 왼쪽 반원' },
    { char: '◛', name: '위 오른쪽 반원' },
    { char: '◜', name: '왼쪽 위 사분원' },
    { char: '◝', name: '오른쪽 위 사분원' },
    { char: '◞', name: '오른쪽 아래 사분원' },
    { char: '◟', name: '왼쪽 아래 사분원' },
    { char: '◠', name: '위 반원 호' },
    { char: '◡', name: '아래 반원 호' },
    { char: '◢', name: '오른쪽 아래 삼각형' },
    { char: '◣', name: '왼쪽 아래 삼각형' },
    { char: '◤', name: '왼쪽 위 삼각형' },
    { char: '◥', name: '오른쪽 위 삼각형' },
    { char: '▰', name: '평행사변형' },
    { char: '▱', name: '흰 평행사변형' }
  ],
  etc: [
    { char: '©', name: '저작권' },
    { char: '®', name: '등록상표' },
    { char: '™', name: '상표' },
    { char: '℗', name: '음반 저작권' },
    { char: '℠', name: '서비스 마크' },
    { char: '§', name: '섹션' },
    { char: '¶', name: '문단' },
    { char: '†', name: '단검' },
    { char: '‡', name: '이중 단검' },
    { char: '※', name: '참고' },
    { char: '⁂', name: '아스테리즘' },
    { char: '⁑', name: '이중 별표' },
    { char: '⁎', name: '낮은 별표' },
    { char: '⁕', name: '꽃 문양' },
    { char: '⁖', name: '삼점' },
    { char: '⁘', name: '사점' },
    { char: '⁙', name: '오점' },
    { char: '⁚', name: '이점' },
    { char: '⁛', name: '사점 마크' },
    { char: '⁜', name: '십자 마크' },
    { char: '⁝', name: '삼점 수직' },
    { char: '⁞', name: '사점 수직' },
    { char: '…', name: '말줄임표' },
    { char: '‥', name: '이점 말줄임' },
    { char: '·', name: '가운뎃점' },
    { char: '•', name: '불릿' },
    { char: '◦', name: '흰 불릿' },
    { char: '‣', name: '삼각 불릿' },
    { char: '⁃', name: '하이픈 불릿' },
    { char: '∴', name: '그러므로' },
    { char: '∵', name: '왜냐하면' },
    { char: '♠', name: '스페이드' },
    { char: '♤', name: '흰 스페이드' },
    { char: '♣', name: '클로버' },
    { char: '♧', name: '흰 클로버' },
    { char: '♥', name: '하트' },
    { char: '♡', name: '흰 하트' },
    { char: '♦', name: '다이아' },
    { char: '♢', name: '흰 다이아' },
    { char: '♩', name: '사분음표' },
    { char: '♪', name: '팔분음표' },
    { char: '♫', name: '연결 팔분음표' },
    { char: '♬', name: '연결 십육분음표' },
    { char: '♭', name: '플랫' },
    { char: '♮', name: '내추럴' },
    { char: '♯', name: '샵' },
    { char: '☀', name: '태양' },
    { char: '☁', name: '구름' },
    { char: '☂', name: '우산' },
    { char: '☃', name: '눈사람' },
    { char: '☄', name: '혜성' },
    { char: '★', name: '검은 별' },
    { char: '☆', name: '흰 별' },
    { char: '☎', name: '전화기' },
    { char: '☏', name: '흰 전화기' },
    { char: '☑', name: '체크박스' },
    { char: '☒', name: '엑스박스' },
    { char: '☓', name: '엑스 마크' },
    { char: '☔', name: '비 우산' },
    { char: '☕', name: '커피' },
    { char: '☘', name: '샴록' },
    { char: '☙', name: '회전 하트 불릿' },
    { char: '☚', name: '왼쪽 검지' },
    { char: '☛', name: '오른쪽 검지' },
    { char: '☜', name: '흰 왼쪽 검지' },
    { char: '☝', name: '흰 위 검지' },
    { char: '☞', name: '흰 오른쪽 검지' },
    { char: '☟', name: '흰 아래 검지' },
    { char: '☠', name: '해골' },
    { char: '☢', name: '방사능' },
    { char: '☣', name: '생물학적 위험' },
    { char: '☤', name: '카두케우스' },
    { char: '☥', name: '앙크' },
    { char: '☦', name: '정교회 십자가' },
    { char: '☧', name: '키로' },
    { char: '☨', name: '로렌 십자가' },
    { char: '☩', name: '예루살렘 십자가' },
    { char: '☪', name: '초승달과 별' },
    { char: '☬', name: '아디 샥티' },
    { char: '☭', name: '낫과 망치' },
    { char: '☮', name: '평화' },
    { char: '☯', name: '음양' },
    { char: '☰', name: '건괘' },
    { char: '☱', name: '태괘' },
    { char: '☲', name: '리괘' },
    { char: '☳', name: '진괘' },
    { char: '☴', name: '손괘' },
    { char: '☵', name: '감괘' },
    { char: '☶', name: '간괘' },
    { char: '☷', name: '곤괘' },
    { char: '☸', name: '법륜' },
    { char: '☹', name: '슬픈 얼굴' },
    { char: '☺', name: '웃는 얼굴' },
    { char: '☻', name: '검은 웃는 얼굴' },
    { char: '☼', name: '태양 모양' },
    { char: '☽', name: '초승달' },
    { char: '☾', name: '그믐달' },
    { char: '♀', name: '여성' },
    { char: '♁', name: '지구' },
    { char: '♂', name: '남성' },
    { char: '⚀', name: '주사위 1' },
    { char: '⚁', name: '주사위 2' },
    { char: '⚂', name: '주사위 3' },
    { char: '⚃', name: '주사위 4' },
    { char: '⚄', name: '주사위 5' },
    { char: '⚅', name: '주사위 6' },
    { char: '⚐', name: '흰 깃발' },
    { char: '⚑', name: '검은 깃발' },
    { char: '⚒', name: '망치와 곡괭이' },
    { char: '⚓', name: '닻' },
    { char: '⚔', name: '검' },
    { char: '⚕', name: '의료' },
    { char: '⚖', name: '저울' },
    { char: '⚗', name: '증류기' },
    { char: '⚘', name: '꽃' },
    { char: '⚙', name: '톱니바퀴' },
    { char: '⚚', name: '헤르메스 지팡이' },
    { char: '⚛', name: '원자' },
    { char: '⚜', name: '백합 문장' },
    { char: '⚝', name: '윤곽 별' },
    { char: '⚠', name: '경고' },
    { char: '⚡', name: '번개' },
    { char: '⚪', name: '흰 원' },
    { char: '⚫', name: '검은 원' },
    { char: '⚬', name: '중간 흰 원' },
    { char: '⚭', name: '결혼' },
    { char: '⚮', name: '이혼' },
    { char: '⚯', name: '비혼' },
    { char: '⚰', name: '관' },
    { char: '⚱', name: '유골함' },
    { char: '⛏', name: '곡괭이' },
    { char: '⛑', name: '헬멧' }
  ]
};

// DOM 요소
let searchInput;
let recentSection;
let recentGrid;
let symbolGrid;
let toast;
let categoryTabs;

// 현재 선택된 카테고리
let currentCategory = 'emoji';

// 최근 복사 기록
let recentSymbols = JSON.parse(localStorage.getItem('recentSymbols')) || [];

// 초기화
function init() {
  // DOM 요소 초기화
  searchInput = document.getElementById('searchInput');
  recentSection = document.getElementById('recentSection');
  recentGrid = document.getElementById('recentGrid');
  symbolGrid = document.getElementById('symbolGrid');
  toast = document.getElementById('toast');
  categoryTabs = document.querySelector('.category-tabs');

  // 초기 카테고리의 이모지 렌더링
  renderSymbols(currentCategory);
  renderRecentSymbols();
  setupEventListeners();
}

// 이벤트 리스너 설정
function setupEventListeners() {
  // 탭 버튼 클릭 (이벤트 위임)
  categoryTabs.addEventListener('click', (e) => {
    const btn = e.target.closest('.tab-btn');
    if (!btn) return;

    // 모든 탭에서 active 제거
    const allTabs = categoryTabs.querySelectorAll('.tab-btn');
    allTabs.forEach(b => b.classList.remove('active'));

    // 클릭된 탭에 active 추가
    btn.classList.add('active');

    // 카테고리 변경
    currentCategory = btn.dataset.category;

    // 검색어 초기화
    searchInput.value = '';

    // 해당 카테고리의 모든 이모지 렌더링
    renderSymbols(currentCategory);
  });

  // 검색
  searchInput.addEventListener('input', (e) => {
    const query = e.target.value.trim().toLowerCase();
    if (query) {
      searchSymbols(query);
    } else {
      renderSymbols(currentCategory);
    }
  });

  // 문자 버튼 클릭 (이벤트 위임) - symbolGrid
  symbolGrid.addEventListener('click', (e) => {
    const btn = e.target.closest('.symbol-btn');
    if (!btn) return;
    handleSymbolClick(btn);
  });

  // 문자 버튼 클릭 (이벤트 위임) - recentGrid
  recentGrid.addEventListener('click', (e) => {
    const btn = e.target.closest('.symbol-btn');
    if (!btn) return;
    handleSymbolClick(btn);
  });
}

// 문자 버튼 클릭 처리
function handleSymbolClick(btn) {
  const char = btn.dataset.char;
  const name = btn.dataset.name;
  copyToClipboard(char, btn);
  addToRecent(char, name);
}

// 문자 렌더링
function renderSymbols(category) {
  const symbols = symbolData[category] || [];
  symbolGrid.innerHTML = symbols.map(s => createSymbolButton(s)).join('');
}

// 검색 결과 렌더링
function searchSymbols(query) {
  const allSymbols = Object.values(symbolData).flat();
  const results = allSymbols.filter(s =>
    s.name.toLowerCase().includes(query) || s.char.includes(query)
  );

  if (results.length === 0) {
    symbolGrid.innerHTML = '<div class="no-results">검색 결과가 없습니다</div>';
  } else {
    symbolGrid.innerHTML = results.map(s => createSymbolButton(s)).join('');
  }
}

// 문자 버튼 생성
function createSymbolButton(symbol) {
  return `<button type="button" class="symbol-btn" data-char="${symbol.char}" data-name="${symbol.name}" data-tooltip="${symbol.name}">${symbol.char}</button>`;
}

// 클립보드 복사
async function copyToClipboard(text, button) {
  try {
    await navigator.clipboard.writeText(text);
    showCopiedFeedback(button);
    showToast();
  } catch (err) {
    // 폴백
    const textarea = document.createElement('textarea');
    textarea.value = text;
    document.body.appendChild(textarea);
    textarea.select();
    document.execCommand('copy');
    document.body.removeChild(textarea);
    showCopiedFeedback(button);
    showToast();
  }
}

// 버튼 피드백
function showCopiedFeedback(button) {
  button.classList.add('copied');
  setTimeout(() => {
    button.classList.remove('copied');
  }, 500);
}

// 토스트 표시
function showToast() {
  toast.classList.add('show');
  setTimeout(() => {
    toast.classList.remove('show');
  }, 1500);
}

// 최근 복사 추가
function addToRecent(char, name) {
  // 중복 제거
  recentSymbols = recentSymbols.filter(s => s.char !== char);
  // 앞에 추가
  recentSymbols.unshift({ char, name });
  // 최대 10개 유지
  if (recentSymbols.length > 10) {
    recentSymbols = recentSymbols.slice(0, 10);
  }
  // 저장
  localStorage.setItem('recentSymbols', JSON.stringify(recentSymbols));
  renderRecentSymbols();
}

// 최근 복사 렌더링
function renderRecentSymbols() {
  if (recentSymbols.length === 0) {
    recentSection.style.display = 'none';
    return;
  }

  recentSection.style.display = 'block';
  recentGrid.innerHTML = recentSymbols.map(s => createSymbolButton(s)).join('');
}

// 페이지 로드 시 초기화
if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', init);
} else {
  init();
}
